# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Timezone
timezone: "Africa/Cairo" # Adjusted to your region

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: "Mr Robot" # Main title
tagline: "Malware Analysis & Reverse Engineering & CTFs Topics" # Tagline of the blog
description: "Exploring The Depths Of Reverse Engineering And Malware Analysis To Decode Cyber Threats And Uncover Hidden Vulnerabilities."

# Fill in the protocol & hostname for your site.
# E.g., 'https://username.github.io', note that it does not end with a '/'.
url: "https://0xMr-Robot.github.io"


github:
  username: 0xMr-Robot # Your GitHub username as per the provided link

twitter:
  username: Eslam_Abbas_1 # Your Twitter username

social:
  name: Eslam Mohamed Abbas
  email: manwelnueur87@gmail.com
  links:
    - https://twitter.com/Eslam_Abbas_1 # Twitter
    - https://github.com/0xMr-Robot # GitHub
    - https://www.linkedin.com/in/eslam-abbas-20aa64213/ # LinkedIn
    - https://www.facebook.com/EslamAbbas # Facebook
    - https://www.youtube.com/channel/UCpJJNDyg3rdFR8YdFt_hZXA # YouTube Channel
    - https://medium.com/@0xMr_Robot # Medium

# Site Verification Settings
webmaster_verifications:
  google: "" # Fill in Google verification code
  bing: "" # Fill in Bing verification code
  yandex: "" # Yandex
  baidu: "" # Baidu
  facebook: "" # Facebook

# ↑ --------------------------
# End of jekyll-seo-tag settings

# Web Analytics Settings
analytics:
  google:
    id: "UA-XXXXXX-Y" # Replace with your Google Analytics ID
  goatcounter:
    id: mr robot

# Page views settings
pageviews:
  provider: goatcounter # or replace with another provider if using different page view tracking

# Prefer color scheme setting.
<<<<<<< HEAD
theme_mode: # [light|dark]
=======
# theme_mode: dark # Set to 'dark' for a darker interface
>>>>>>> 2375d1405c65d60175b834e1071a742cec17a837

# The CDN endpoint for media resources
cdn: ""

# Sidebar avatar
avatar: https://avatars.githubusercontent.com/u/128882704?v=4 # Replace with the actual path to your avatar image

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: https://avatars.githubusercontent.com/u/128882704?v=4 # Path to social preview image

# Global switch for Table of Contents (TOC) in posts
toc: true

# Comment system
comments:
  provider: giscus # You can use Disqus or Utterances if preferred
  giscus:
    repo: 0xMr-Robot/0xMr-Robot.github.io # GitHub repo for Giscus comments
    repo_id: your-repo-id # Add your repo ID from Giscus setup
    category: General # Category for Giscus comments
    category_id: your-category-id # Category ID from Giscus
    mapping: pathname # Choose your mapping method
    reactions_enabled: 1 # Enable reactions in Giscus

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: false # Change to true if you are self-hosting assets

# PWA Configuration
pwa:
  enabled: true # PWA support is enabled
  cache:
    enabled: true
    deny_paths: # Add paths here to exclude from caching
      # - "/example"

# Pagination for posts
paginate: 10

# The base URL of your site
baseurl: "" # Leave blank unless hosting on a subdirectory

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts
      toc: true # Enable Table of Contents in posts
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
