# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Timezone
timezone: "Africa/Cairo" # Adjusted to your region

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: MrRobot # Main title
tagline: Unraveling Code, Defeating Threats. # Tagline of the blog
description: >- Step into the realm of cybersecurity with Mr. Robot, a blog dedicated to exposing the hidden layers of code and the strategies behind modern cyber threats. Here, we delve into the heart of reverse engineering, stripping down software to its bare essentials to uncover the secrets within. Whether it is deconstructing malicious payloads or demystifying complex software protections, you will find in-depth tutorials and guides that reveal how things work behind the scenes.
Our focus on malware analysis brings the world of malicious code to light—breaking down the methodologies used by attackers, understanding their tactics, and preparing defenses against future threats. You Will discover how the smallest piece of code can lead to the biggest breaches, and more importantly, how to stop them.
For those looking to challenge their skills, we also dive into Capture the Flag (CTF) competitions, offering tips, strategies, and walkthroughs on tackling cryptographic puzzles, binary exploitation, and digital forensics. CTFs are not just a test of skill but an exhilarating way to think like an attacker while sharpening your defensive tactics.
Join a community of like-minded cybersecurity professionals, hobbyists, and learners, as we unravel the complexities of the digital battlefield and arm ourselves with the knowledge to protect, defend, and innovate. Together, we decode the future.

# Fill in the protocol & hostname for your site.
# E.g., 'https://username.github.io', note that it does not end with a '/'.
url: "https://0xMr-Robot.github.io"

github:
  username: 0xMr-Robot # Your GitHub username as per the provided link

twitter:
  username: Eslam_Abbas_1 # Your Twitter username

social:
  name: Eslam Mohamed Abbas # Full name as displayed
  email: manwelnueur87@gmail.com # Contact email address
  links:
    - https://twitter.com/Eslam_Abbas_1 # Twitter account
    - https://github.com/0xMr-Robot # Your GitHub profile
    - https://www.linkedin.com/in/eslam-abbas-20aa64213/ # LinkedIn profile
    - https://t.me/EslamAbbas_1 # Telegram account
    - https://medium.com/@0xMr_Robot # Medium blog

# Site Verification Settings
webmaster_verifications:
  google: your-google-verification-code # Fill in Google verification code
  bing: your-bing-verification-code # Fill in Bing verification code
  yandex: your-yandex-verification-code # Yandex
  baidu: your-baidu-verification-code # Baidu
  facebook: your-facebook-verification-code # Facebook

# ↑ --------------------------
# End of jekyll-seo-tag settings

# Web Analytics Settings
analytics:
  google:
    id: "UA-XXXXXX-Y" # Replace with your Google Analytics ID
  goatcounter:
    id: # Fill in GoatCounter ID if used

# Page views settings
pageviews:
  provider: goatcounter # or replace with another provider if using different page view tracking

# Prefer color scheme setting.
theme_mode: dark # Set to 'dark' for a darker interface

# The CDN endpoint for media resources
cdn: ""

# Sidebar avatar
avatar: https://avatars.githubusercontent.com/u/128882704?v=4 # Replace with the actual path to your avatar image

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: https://avatars.githubusercontent.com/u/128882704?v=4 # Path to social preview image

# Global switch for Table of Contents (TOC) in posts
toc: true

# Comment system
comments:
  provider: giscus # You can use Disqus or Utterances if preferred
  giscus:
    repo: 0xMr-Robot/0xMr-Robot.github.io # GitHub repo for Giscus comments
    repo_id: your-repo-id # Add your repo ID from Giscus setup
    category: General # Category for Giscus comments
    category_id: your-category-id # Category ID from Giscus
    mapping: pathname # Choose your mapping method
    reactions_enabled: 1 # Enable reactions in Giscus

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: false # Change to true if you are self-hosting assets

# PWA Configuration
pwa:
  enabled: true # PWA support is enabled
  cache:
    enabled: true
    deny_paths: # Add paths here to exclude from caching
      # - "/example"

# Pagination for posts
paginate: 10

# The base URL of your site
baseurl: "" # Leave blank unless hosting on a subdirectory

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts
      toc: true # Enable Table of Contents in posts
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
